name: MakeUse
main: me.main__.MakeUse.MakeUse
version: 1.1.0
author: main()
description: With MakeUse you can make somebody use a command! (e.g. make somebody read the rules)
softdepend: [Permissions]
commands:
    makeuse:
        description: Make somebody use a command!
        permission: makeuse
        usage: |
            /<command> [user] [command]